package org.omg.CORBA.ContainerPackage;


/**
* org/omg/CORBA/ContainerPackage/Description.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class Description implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.Contained contained_object = null;
  public org.omg.CORBA.DefinitionKind kind = null;
  public org.omg.CORBA.Any value = null;

  public Description ()
  {
  } // ctor

  public Description (org.omg.CORBA.Contained _contained_object, org.omg.CORBA.DefinitionKind _kind, org.omg.CORBA.Any _value)
  {
    contained_object = _contained_object;
    kind = _kind;
    value = _value;
  } // ctor

} // class Description
