package org.omg.SendingContext;


/**
* org/omg/SendingContext/CodeBasePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/SendingContext.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


// services in the future
public class CodeBasePOATie extends CodeBasePOA
{

  // Constructors

  public CodeBasePOATie ( org.omg.SendingContext.CodeBaseOperations delegate ) {
      this._impl = delegate;
  }
  public CodeBasePOATie ( org.omg.SendingContext.CodeBaseOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.omg.SendingContext.CodeBaseOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.omg.SendingContext.CodeBaseOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }

  // Operation to obtain the IR from the sending context
  public org.omg.CORBA.Repository get_ir ()
  {
    return _impl.get_ir();
  } // get_ir


  // Operations to obtain a location of the implementation code
  public String implementation (String x)
  {
    return _impl.implementation(x);
  } // implementation

  public String implementationx (String x)
  {
    return _impl.implementationx(x);
  } // implementationx

  public String[] implementations (String[] x)
  {
    return _impl.implementations(x);
  } // implementations


  // the same information
  public org.omg.CORBA.ValueDefPackage.FullValueDescription meta (String x)
  {
    return _impl.meta(x);
  } // meta

  public org.omg.CORBA.ValueDefPackage.FullValueDescription[] metas (String[] x)
  {
    return _impl.metas(x);
  } // metas


  // information
  public String[] bases (String x)
  {
    return _impl.bases(x);
  } // bases

  private org.omg.SendingContext.CodeBaseOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class CodeBasePOATie
