package org.omg.SendingContext;


/**
* org/omg/SendingContext/RunTimePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/SendingContext.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public abstract class RunTimePOA extends org.omg.PortableServer.Servant
 implements org.omg.SendingContext.RunTimeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.org/SendingContext/RunTime:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RunTime _this() 
  {
    return RunTimeHelper.narrow(
    super._this_object());
  }

  public RunTime _this(org.omg.CORBA.ORB orb) 
  {
    return RunTimeHelper.narrow(
    super._this_object(orb));
  }


} // class RunTimePOA
