package org.omg.SendingContext;


/**
* org/omg/SendingContext/RunTimeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/SendingContext.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface RunTimeOperations 
{
} // interface RunTimeOperations
