package org.omg.SendingContext;


/**
* org/omg/SendingContext/RunTimePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/SendingContext.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public class RunTimePOATie extends RunTimePOA
{

  // Constructors

  public RunTimePOATie ( org.omg.SendingContext.RunTimeOperations delegate ) {
      this._impl = delegate;
  }
  public RunTimePOATie ( org.omg.SendingContext.RunTimeOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.omg.SendingContext.RunTimeOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.omg.SendingContext.RunTimeOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  private org.omg.SendingContext.RunTimeOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RunTimePOATie
