package org.omg.PortableInterceptor;

/**
* org/omg/PortableInterceptor/InterceptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/Interceptors.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


/**
   * All Portable Interceptors implement Interceptor.
   */
public final class InterceptorHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.PortableInterceptor.Interceptor value = null;

  public InterceptorHolder ()
  {
  }

  public InterceptorHolder (org.omg.PortableInterceptor.Interceptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.PortableInterceptor.InterceptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.PortableInterceptor.InterceptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.PortableInterceptor.InterceptorHelper.type ();
  }

}
