package org.omg.IOP;


/**
* org/omg/IOP/CodeSets.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/IOP.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface CodeSets
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CONV_FRAME.CodeSetContext</code> defined in 
       * Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
       */
  public static final int value = (int)(1L);
}
