package org.omg.IOP;


/**
* org/omg/IOP/FORWARDED_IDENTITY.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/IOP.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface FORWARDED_IDENTITY
{

  /**
       * For information on <code>FORWARDED_IDENTITY</code> refer to the 
       * Firewall specification - orbos/98-05-04.
       */
  public static final int value = (int)(8L);
}
