package org.omg.IOP;


/**
* org/omg/IOP/LogicalThreadId.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/IOP.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface LogicalThreadId
{

  /**
       * DCOM-CORBA Interworking uses three service contexts as defined in 
       * "DCOM-CORBA Interworking" in the "Interoperability with non-CORBA 
       * Systems" chapter.
       * <p>
       * <code>LogicalThreadId</code>, carries a CDR encapsulation of 
       * the <code>struct CosBridging.LogicalThreadId</code> as described 
       * in Section 20.10, "Thread Identification," on page 20-21.
       */
  public static final int value = (int)(4L);
}
