package org.omg.IOP;


/**
* org/omg/IOP/SendingContextRunTime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/IOP.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface SendingContextRunTime
{

  /**
       * Identifies a CDR encapsulation of the IOR of the 
       * <code>SendingContext.RunTime</code> object (see Section 5.6, "Access 
       * to the Sending Context Run Time," on page 5-15). 
       */
  public static final int value = (int)(6L);
}
