package org.omg.IOP;


/**
* org/omg/IOP/TAG_CODE_SETS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/IOP.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface TAG_CODE_SETS
{

  /**
       * The code set component of the IOR multi-component profile structure
       * contains:
       * <ul>
       *   <li>server's native char code set and conversion code sets, and</li>
       *   <li>server's native wchar code set and conversion code sets.</li>
       * </ul>
       * Both char and wchar conversion code sets are listed in order of 
       * preference.
       */
  public static final int value = (int)(1L);
}
