package org.omg.TimeBase;

/**
* org/omg/TimeBase/IntervalTHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/TimeBase.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class IntervalTHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.TimeBase.IntervalT value = null;

  public IntervalTHolder ()
  {
  }

  public IntervalTHolder (org.omg.TimeBase.IntervalT initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.TimeBase.IntervalTHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.TimeBase.IntervalTHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.TimeBase.IntervalTHelper.type ();
  }

}
