package org.omg.Messaging;


/**
* org/omg/Messaging/PolicyValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/Messaging.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class PolicyValue implements org.omg.CORBA.portable.IDLEntity
{
  public int ptype = (int)0;
  public byte pvalue[] = null;

  public PolicyValue ()
  {
  } // ctor

  public PolicyValue (int _ptype, byte[] _pvalue)
  {
    ptype = _ptype;
    pvalue = _pvalue;
  } // ctor

} // class PolicyValue
