package org.omg.Messaging;


/**
* org/omg/Messaging/PolicyValueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/Messaging.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

abstract public class PolicyValueHelper
{
  private static String  _id = "IDL:omg.org/Messaging/PolicyValue:1.0";

  public static void insert (org.omg.CORBA.Any a, org.omg.Messaging.PolicyValue that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.omg.Messaging.PolicyValue extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.omg.CORBA.PolicyTypeHelper.id (), "PolicyType", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "ptype",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "pvalue",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.omg.Messaging.PolicyValueHelper.id (), "PolicyValue", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.omg.Messaging.PolicyValue read (org.omg.CORBA.portable.InputStream istream)
  {
    org.omg.Messaging.PolicyValue value = new org.omg.Messaging.PolicyValue ();
    value.ptype = istream.read_ulong ();
    int _len0 = istream.read_long ();
    value.pvalue = new byte[_len0];
    istream.read_octet_array (value.pvalue, 0, _len0);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.omg.Messaging.PolicyValue value)
  {
    ostream.write_ulong (value.ptype);
    ostream.write_long (value.pvalue.length);
    ostream.write_octet_array (value.pvalue, 0, value.pvalue.length);
  }

}
