package org.omg.Messaging;


/**
* org/omg/Messaging/QUEUE_ORDER_POLICY_TYPE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/Messaging.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface QUEUE_ORDER_POLICY_TYPE
{

  // Router Delivery-ordering Policy (default = ORDER_TEMPORAL)
  public static final int value = (int)(35L);
}
