package org.omg.Messaging;


/**
* org/omg/Messaging/RELATIVE_REQ_TIMEOUT_POLICY_TYPE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/Messaging.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface RELATIVE_REQ_TIMEOUT_POLICY_TYPE
{
  public static final int value = (int)(31L);
}
