package org.omg.Messaging;


/**
* org/omg/Messaging/ReplyStartTimePolicyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/Messaging.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface ReplyStartTimePolicyOperations  extends org.omg.CORBA.PolicyOperations
{
  org.omg.TimeBase.UtcT start_time ();
} // interface ReplyStartTimePolicyOperations
