package org.omg.Messaging;


/**
* org/omg/Messaging/ROUTE_STORE_AND_FORWARD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/Messaging.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface ROUTE_STORE_AND_FORWARD
{
  public static final short value = (short)(2);
}
