package org.omg.Messaging;


/**
* org/omg/Messaging/RoutingTypeRangeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/Messaging.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

abstract public class RoutingTypeRangeHelper
{
  private static String  _id = "IDL:omg.org/Messaging/RoutingTypeRange:1.0";

  public static void insert (org.omg.CORBA.Any a, org.omg.Messaging.RoutingTypeRange that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.omg.Messaging.RoutingTypeRange extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.omg.Messaging.RoutingTypeHelper.id (), "RoutingType", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "min",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.omg.Messaging.RoutingTypeHelper.id (), "RoutingType", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "max",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.omg.Messaging.RoutingTypeRangeHelper.id (), "RoutingTypeRange", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.omg.Messaging.RoutingTypeRange read (org.omg.CORBA.portable.InputStream istream)
  {
    org.omg.Messaging.RoutingTypeRange value = new org.omg.Messaging.RoutingTypeRange ();
    value.min = istream.read_short ();
    value.max = istream.read_short ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.omg.Messaging.RoutingTypeRange value)
  {
    ostream.write_short (value.min);
    ostream.write_short (value.max);
  }

}
