package org.omg.DynamicAny.DynAnyPackage;

/**
* org/omg/DynamicAny/DynAnyPackage/InvalidValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/DynamicAny.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class InvalidValueHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.DynamicAny.DynAnyPackage.InvalidValue value = null;

  public InvalidValueHolder ()
  {
  }

  public InvalidValueHolder (org.omg.DynamicAny.DynAnyPackage.InvalidValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.DynamicAny.DynAnyPackage.InvalidValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.DynamicAny.DynAnyPackage.InvalidValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.DynamicAny.DynAnyPackage.InvalidValueHelper.type ();
  }

}
