package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/ControlPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public class ControlPOATie extends ControlPOA
{

  // Constructors

  public ControlPOATie ( org.omg.CosTransactions.ControlOperations delegate ) {
      this._impl = delegate;
  }
  public ControlPOATie ( org.omg.CosTransactions.ControlOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.omg.CosTransactions.ControlOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.omg.CosTransactions.ControlOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public org.omg.CosTransactions.Terminator get_terminator () throws org.omg.CosTransactions.Unavailable
  {
    return _impl.get_terminator();
  } // get_terminator

  public org.omg.CosTransactions.Coordinator get_coordinator () throws org.omg.CosTransactions.Unavailable
  {
    return _impl.get_coordinator();
  } // get_coordinator

  private org.omg.CosTransactions.ControlOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ControlPOATie
