package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/HeuristicHazard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class HeuristicHazard extends org.omg.CORBA.UserException
{

  public HeuristicHazard ()
  {
    super(HeuristicHazardHelper.id());
  } // ctor


  public HeuristicHazard (String $reason)
  {
    super(HeuristicHazardHelper.id() + "  " + $reason);
  } // ctor

} // class HeuristicHazard
