package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/HeuristicMixed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class HeuristicMixed extends org.omg.CORBA.UserException
{

  public HeuristicMixed ()
  {
    super(HeuristicMixedHelper.id());
  } // ctor


  public HeuristicMixed (String $reason)
  {
    super(HeuristicMixedHelper.id() + "  " + $reason);
  } // ctor

} // class HeuristicMixed
