package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/NoTransaction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class NoTransaction extends org.omg.CORBA.UserException
{

  public NoTransaction ()
  {
    super(NoTransactionHelper.id());
  } // ctor


  public NoTransaction (String $reason)
  {
    super(NoTransactionHelper.id() + "  " + $reason);
  } // ctor

} // class NoTransaction
