package org.omg.CosTransactions;

/**
* org/omg/CosTransactions/PropagationContextHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class PropagationContextHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CosTransactions.PropagationContext value = null;

  public PropagationContextHolder ()
  {
  }

  public PropagationContextHolder (org.omg.CosTransactions.PropagationContext initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CosTransactions.PropagationContextHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CosTransactions.PropagationContextHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CosTransactions.PropagationContextHelper.type ();
  }

}
