package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/RecoveryCoordinatorPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public class RecoveryCoordinatorPOATie extends RecoveryCoordinatorPOA
{

  // Constructors

  public RecoveryCoordinatorPOATie ( org.omg.CosTransactions.RecoveryCoordinatorOperations delegate ) {
      this._impl = delegate;
  }
  public RecoveryCoordinatorPOATie ( org.omg.CosTransactions.RecoveryCoordinatorOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.omg.CosTransactions.RecoveryCoordinatorOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.omg.CosTransactions.RecoveryCoordinatorOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public org.omg.CosTransactions.Status replay_completion (org.omg.CosTransactions.Resource r) throws org.omg.CosTransactions.NotPrepared
  {
    return _impl.replay_completion(r);
  } // replay_completion

  private org.omg.CosTransactions.RecoveryCoordinatorOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RecoveryCoordinatorPOATie
