package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/RecoveryCoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface RecoveryCoordinatorOperations 
{
  org.omg.CosTransactions.Status replay_completion (org.omg.CosTransactions.Resource r) throws org.omg.CosTransactions.NotPrepared;
} // interface RecoveryCoordinatorOperations
