package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/ResourcePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public class ResourcePOATie extends ResourcePOA
{

  // Constructors

  public ResourcePOATie ( org.omg.CosTransactions.ResourceOperations delegate ) {
      this._impl = delegate;
  }
  public ResourcePOATie ( org.omg.CosTransactions.ResourceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public org.omg.CosTransactions.ResourceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (org.omg.CosTransactions.ResourceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public org.omg.CosTransactions.Vote prepare () throws org.omg.CosTransactions.HeuristicMixed, org.omg.CosTransactions.HeuristicHazard
  {
    return _impl.prepare();
  } // prepare

  public void rollback () throws org.omg.CosTransactions.HeuristicCommit, org.omg.CosTransactions.HeuristicMixed, org.omg.CosTransactions.HeuristicHazard
  {
    _impl.rollback();
  } // rollback

  public void commit () throws org.omg.CosTransactions.NotPrepared, org.omg.CosTransactions.HeuristicRollback, org.omg.CosTransactions.HeuristicMixed, org.omg.CosTransactions.HeuristicHazard
  {
    _impl.commit();
  } // commit

  public void commit_one_phase () throws org.omg.CosTransactions.HeuristicHazard
  {
    _impl.commit_one_phase();
  } // commit_one_phase

  public void forget ()
  {
    _impl.forget();
  } // forget

  private org.omg.CosTransactions.ResourceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ResourcePOATie
