package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/SubtransactionsUnavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class SubtransactionsUnavailable extends org.omg.CORBA.UserException
{

  public SubtransactionsUnavailable ()
  {
    super(SubtransactionsUnavailableHelper.id());
  } // ctor


  public SubtransactionsUnavailable (String $reason)
  {
    super(SubtransactionsUnavailableHelper.id() + "  " + $reason);
  } // ctor

} // class SubtransactionsUnavailable
