package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/SynchronizationUnavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class SynchronizationUnavailable extends org.omg.CORBA.UserException
{

  public SynchronizationUnavailable ()
  {
    super(SynchronizationUnavailableHelper.id());
  } // ctor


  public SynchronizationUnavailable (String $reason)
  {
    super(SynchronizationUnavailableHelper.id() + "  " + $reason);
  } // ctor

} // class SynchronizationUnavailable
