package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/SynchronizationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


// Inheritance from TransactionalObject is for backward compatability //
public interface SynchronizationOperations 
{
  void before_completion ();
  void after_completion (org.omg.CosTransactions.Status s);
} // interface SynchronizationOperations
