package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/TerminatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface TerminatorOperations 
{
  void commit (boolean report_heuristics) throws org.omg.CosTransactions.HeuristicMixed, org.omg.CosTransactions.HeuristicHazard;
  void rollback ();
} // interface TerminatorOperations
