package org.omg.CosTransactions;


/**
* org/omg/CosTransactions/TransIdentity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/CosTransactions.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class TransIdentity implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CosTransactions.Coordinator coord = null;
  public org.omg.CosTransactions.Terminator term = null;
  public org.omg.CosTransactions.otid_t otid = null;

  public TransIdentity ()
  {
  } // ctor

  public TransIdentity (org.omg.CosTransactions.Coordinator _coord, org.omg.CosTransactions.Terminator _term, org.omg.CosTransactions.otid_t _otid)
  {
    coord = _coord;
    term = _term;
    otid = _otid;
  } // ctor

} // class TransIdentity
