package org.omg.CORBA;


/**
* org/omg/CORBA/AliasDefOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface AliasDefOperations  extends org.omg.CORBA.TypedefDefOperations
{
  org.omg.CORBA.IDLType original_type_def ();
  void original_type_def (org.omg.CORBA.IDLType newOriginal_type_def);
} // interface AliasDefOperations
