package org.omg.CORBA;


/**
* org/omg/CORBA/AttributeDescription.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class AttributeDescription implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String id = null;
  public String defined_in = null;
  public String version = null;
  public org.omg.CORBA.TypeCode type = null;
  public org.omg.CORBA.AttributeMode mode = null;

  public AttributeDescription ()
  {
  } // ctor

  public AttributeDescription (String _name, String _id, String _defined_in, String _version, org.omg.CORBA.TypeCode _type, org.omg.CORBA.AttributeMode _mode)
  {
    name = _name;
    id = _id;
    defined_in = _defined_in;
    version = _version;
    type = _type;
    mode = _mode;
  } // ctor

} // class AttributeDescription
