package org.omg.CORBA;

/**
* org/omg/CORBA/AttributeDescriptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class AttributeDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.AttributeDescription value = null;

  public AttributeDescriptionHolder ()
  {
  }

  public AttributeDescriptionHolder (org.omg.CORBA.AttributeDescription initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.AttributeDescriptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.AttributeDescriptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.AttributeDescriptionHelper.type ();
  }

}
