package org.omg.CORBA;

/**
* org/omg/CORBA/ConstantDescriptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class ConstantDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.ConstantDescription value = null;

  public ConstantDescriptionHolder ()
  {
  }

  public ConstantDescriptionHolder (org.omg.CORBA.ConstantDescription initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.ConstantDescriptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.ConstantDescriptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.ConstantDescriptionHelper.type ();
  }

}
