package org.omg.CORBA;


/**
* org/omg/CORBA/ContainedPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public abstract class ContainedPOA extends org.omg.PortableServer.Servant
 implements org.omg.CORBA.ContainedOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id", new java.lang.Integer (0));
    _methods.put ("_set_id", new java.lang.Integer (1));
    _methods.put ("_get_name", new java.lang.Integer (2));
    _methods.put ("_set_name", new java.lang.Integer (3));
    _methods.put ("_get_version", new java.lang.Integer (4));
    _methods.put ("_set_version", new java.lang.Integer (5));
    _methods.put ("_get_defined_in", new java.lang.Integer (6));
    _methods.put ("_get_absolute_name", new java.lang.Integer (7));
    _methods.put ("_get_containing_repository", new java.lang.Integer (8));
    _methods.put ("describe", new java.lang.Integer (9));
    _methods.put ("move", new java.lang.Integer (10));
    _methods.put ("_get_def_kind", new java.lang.Integer (11));
    _methods.put ("destroy", new java.lang.Integer (12));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // read/write interface
       case 0:  // org/omg/CORBA/Contained/_get_id
       {
         String $result = null;
         $result = this.id ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // read/write interface
       case 1:  // org/omg/CORBA/Contained/_set_id
       {
         String newId = org.omg.CORBA.RepositoryIdHelper.read (in);
         this.id (newId);
         out = $rh.createReply();
         break;
       }

       case 2:  // org/omg/CORBA/Contained/_get_name
       {
         String $result = null;
         $result = this.name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // org/omg/CORBA/Contained/_set_name
       {
         String newName = org.omg.CORBA.IdentifierHelper.read (in);
         this.name (newName);
         out = $rh.createReply();
         break;
       }

       case 4:  // org/omg/CORBA/Contained/_get_version
       {
         String $result = null;
         $result = this.version ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // org/omg/CORBA/Contained/_set_version
       {
         String newVersion = org.omg.CORBA.VersionSpecHelper.read (in);
         this.version (newVersion);
         out = $rh.createReply();
         break;
       }


  // read interface
       case 6:  // org/omg/CORBA/Contained/_get_defined_in
       {
         org.omg.CORBA.Container $result = null;
         $result = this.defined_in ();
         out = $rh.createReply();
         org.omg.CORBA.ContainerHelper.write (out, $result);
         break;
       }

       case 7:  // org/omg/CORBA/Contained/_get_absolute_name
       {
         String $result = null;
         $result = this.absolute_name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // org/omg/CORBA/Contained/_get_containing_repository
       {
         org.omg.CORBA.Repository $result = null;
         $result = this.containing_repository ();
         out = $rh.createReply();
         org.omg.CORBA.RepositoryHelper.write (out, $result);
         break;
       }

       case 9:  // org/omg/CORBA/Contained/describe
       {
         org.omg.CORBA.ContainedPackage.Description $result = null;
         $result = this.describe ();
         out = $rh.createReply();
         org.omg.CORBA.ContainedPackage.DescriptionHelper.write (out, $result);
         break;
       }


  // write interface
       case 10:  // org/omg/CORBA/Contained/move
       {
         org.omg.CORBA.Container new_container = org.omg.CORBA.ContainerHelper.read (in);
         String new_name = org.omg.CORBA.IdentifierHelper.read (in);
         String new_version = org.omg.CORBA.VersionSpecHelper.read (in);
         this.move (new_container, new_name, new_version);
         out = $rh.createReply();
         break;
       }


  // read interface
       case 11:  // org/omg/CORBA/IRObject/_get_def_kind
       {
         org.omg.CORBA.DefinitionKind $result = null;
         $result = this.def_kind ();
         out = $rh.createReply();
         org.omg.CORBA.DefinitionKindHelper.write (out, $result);
         break;
       }


  // write interface
       case 12:  // org/omg/CORBA/IRObject/destroy
       {
         this.destroy ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.org/CORBA/Contained:1.0", 
    "IDL:CORBA/IRObject:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Contained _this() 
  {
    return ContainedHelper.narrow(
    super._this_object());
  }

  public Contained _this(org.omg.CORBA.ORB orb) 
  {
    return ContainedHelper.narrow(
    super._this_object(orb));
  }


} // class ContainedPOA
