package org.omg.CORBA;


/**
* org/omg/CORBA/EnumDefOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface EnumDefOperations  extends org.omg.CORBA.TypedefDefOperations
{
  String[] members ();
  void members (String[] newMembers);
} // interface EnumDefOperations
