package org.omg.CORBA;


/**
* org/omg/CORBA/NativeDefOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


// orbos 98-01-18: Objects By Value -- end
public interface NativeDefOperations  extends org.omg.CORBA.TypedefDefOperations
{
} // interface NativeDefOperations
