package org.omg.CORBA;


/**
* org/omg/CORBA/PrimitiveDefOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public interface PrimitiveDefOperations  extends org.omg.CORBA.IDLTypeOperations
{
  org.omg.CORBA.PrimitiveKind kind ();
} // interface PrimitiveDefOperations
