package org.omg.CORBA;

/**
* org/omg/CORBA/PrimitiveDefHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class PrimitiveDefHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.PrimitiveDef value = null;

  public PrimitiveDefHolder ()
  {
  }

  public PrimitiveDefHolder (org.omg.CORBA.PrimitiveDef initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.PrimitiveDefHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.PrimitiveDefHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.PrimitiveDefHelper.type ();
  }

}
