package org.omg.CORBA;

/**
* org/omg/CORBA/StructDefHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/ir.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/

public final class StructDefHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.StructDef value = null;

  public StructDefHolder ()
  {
  }

  public StructDefHolder (org.omg.CORBA.StructDef initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.StructDefHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.StructDefHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.StructDefHelper.type ();
  }

}
