package org.omg.DynamicAny;

/**
* org/omg/DynamicAny/DynSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/DynamicAny.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


/**
    * DynSequence objects support the manipulation of IDL sequences.
    */
public final class DynSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.DynamicAny.DynSequence value = null;

  public DynSequenceHolder ()
  {
  }

  public DynSequenceHolder (org.omg.DynamicAny.DynSequence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.DynamicAny.DynSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.DynamicAny.DynSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.DynamicAny.DynSequenceHelper.type ();
  }

}
