package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynValueBoxHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/DynamicAny.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


/**
    * DynValueBox objects support the manipulation of IDL boxed value types.
    * The DynValueBox interface can represent both null and non-null value types.
    * For a DynValueBox representing a non-null value type, the DynValueBox has a single component
    * of the boxed type. A DynValueBox representing a null value type has no components
    * and a current position of -1.
    */
abstract public class DynValueBoxHelper
{
  private static String  _id = "IDL:omg.org/DynamicAny/DynValueBox:1.0";

  public static void insert (org.omg.CORBA.Any a, org.omg.DynamicAny.DynValueBox that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.omg.DynamicAny.DynValueBox extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.omg.DynamicAny.DynValueBoxHelper.id (), "DynValueBox");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.omg.DynamicAny.DynValueBox read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DynValueBoxStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.omg.DynamicAny.DynValueBox value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.omg.DynamicAny.DynValueBox narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.omg.DynamicAny.DynValueBox)
      return (org.omg.DynamicAny.DynValueBox)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.omg.DynamicAny._DynValueBoxStub stub = new org.omg.DynamicAny._DynValueBoxStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static org.omg.DynamicAny.DynValueBox unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.omg.DynamicAny.DynValueBox)
      return (org.omg.DynamicAny.DynValueBox)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.omg.DynamicAny._DynValueBoxStub stub = new org.omg.DynamicAny._DynValueBoxStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
