package org.omg.DynamicAny;

/**
* org/omg/DynamicAny/DynValueCommonHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/DynamicAny.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


/**
    * DynValueCommon provides operations supported by both the DynValue and DynValueBox interfaces.
    */
public final class DynValueCommonHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.DynamicAny.DynValueCommon value = null;

  public DynValueCommonHolder ()
  {
  }

  public DynValueCommonHolder (org.omg.DynamicAny.DynValueCommon initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.DynamicAny.DynValueCommonHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.DynamicAny.DynValueCommonHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.DynamicAny.DynValueCommonHelper.type ();
  }

}
