package org.omg.PortableServer;


/**
* org/omg/PortableServer/IdUniquenessPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/poa.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


/**
         * The IdUniquenessPolicy specifies whether the servants 
         * activated in the created POA must have unique object i
         * identities. The default is UNIQUE_ID.
         */
public interface IdUniquenessPolicy extends IdUniquenessPolicyOperations, org.omg.CORBA.Policy, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdUniquenessPolicy
