package org.omg.PortableServer;

/**
* org/omg/PortableServer/LifespanPolicyValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/poa.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


/**
         * The LifespanPolicyValue can have the following values.
         * TRANSIENT - The objects implemented in the POA 
         * cannot outlive the POA instance in which they are 
         * first created. 
         * PERSISTENT - The objects implemented in the POA can 
         * outlive the process in which they are first created. 
         */
public final class LifespanPolicyValueHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.PortableServer.LifespanPolicyValue value = null;

  public LifespanPolicyValueHolder ()
  {
  }

  public LifespanPolicyValueHolder (org.omg.PortableServer.LifespanPolicyValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.PortableServer.LifespanPolicyValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.PortableServer.LifespanPolicyValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.PortableServer.LifespanPolicyValueHelper.type ();
  }

}
