package org.omg.PortableServer;


/**
* org/omg/PortableServer/POAListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/russgold/projects/glassfish/glassfish-corba/target/checkout/omgapi/src/main/idl/poa.idl
* Friday, July 14, 2017 11:15:15 AM EDT
*/


/**
         * List of POAs
         */
public final class POAListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.PortableServer.POA value[] = null;

  public POAListHolder ()
  {
  }

  public POAListHolder (org.omg.PortableServer.POA[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.PortableServer.POAListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.PortableServer.POAListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.PortableServer.POAListHelper.type ();
  }

}
